semana8/mvc_crud/app/models/user_model.py
from database import db


# `db.Model` es una clase base para todos los modelos de SQLAlchemy
# Define la clase `User` que hereda de `db.Model`
# `User` representa la tabla `users` en la base de datos
class User(db.Model):
    __tablename__ = "users"
    # Define las columnas de la tabla `users`
    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String(50), nullable=False)
    last_name = db.Column(db.String(50), nullable=False)

    # Inicializa la clase `User`
    def __init__(self, first_name, last_name):
        self.first_name = first_name
        self.last_name = last_name

    # Guarda un usuario en la base de datos
    def save(self):
        db.session.add(self)
        db.session.commit()

    # Obtiene todos los usuarios de la base de datos
    @staticmethod
    def get_all():
        return User.query.all()

    # Obtiene un usuario por su id
    @staticmethod
    def get_by_id(id):
        return User.query.get(id)

    # Actualiza un usuario en la base de datos
    def update(self):
        db.session.commit()

    # Elimina un usuario de la base de datos
    def delete(self):
        db.session.delete(self)
        db.session.commit()

semana8/mvc_crud/app/controllers/user_controller.py
from flask import Blueprint, request, redirect, url_for

# Importamos la vista de usuarios
from views import user_view

# Importamos el modelo de usuario
from models.user_model import User

# Un Blueprint es un objeto que agrupa
# rutas y vistas
user_bp = Blueprint("user", __name__)


# Ruta de la página raíz redirige a la vista de usuarios
@user_bp.route("/")
def index():
    return redirect(url_for("user.list_users"))


@user_bp.route("/users")
def list_users():
    # Obtenemos todos los usuarios
    users = User.get_all()
    # Llamamos a la vista de usuarios
    return user_view.usuarios(users)


# Definimos la ruta "/users" asociada a la función registro
# que nos devuelve la vista de registro
@user_bp.route("/users/create", methods=["GET", "POST"])
def create_user():
    if request.method == "POST":
        # Obtenemos los datos del formulario
        first_name = request.form["first_name"]
        last_name = request.form["last_name"]
        # Creamos un nuevo usuario
        user = User(first_name, last_name)
        # Guardamos el usuario
        user.save()
        return redirect(url_for("user.list_users"))
    # Llamamos a la vista de registro
    return user_view.registro()


# Actualizamos la información del usuario por su id
# Ya estamos en la vista de actualizar
# por lo que obtenemos los datos del formulario
# y actualizamos la información del usuario
@user_bp.route("/users/<int:id>/update", methods=["GET", "POST"])
def update_user(id):
    user = User.get_by_id(id)
    if not user:
        return "Usuario no encontrado", 404
    if request.method == "POST":
        # Obtenemos los datos del formulario
        first_name = request.form["first_name"]
        last_name = request.form["last_name"]
        # Actualizamos los datos del usuario
        user.first_name = first_name
        user.last_name = last_name
        # Guardamos los cambios
        user.update()
        return redirect(url_for("user.list_users"))
    return user_view.actualizar(user)


@user_bp.route("/users/<int:id>/delete")
def delete_user(id):
    user = User.get_by_id(id)
    if not user:
        return "Usuario no encontrado", 404
    user.delete()
    return redirect(url_for("user.list_users"))

semana8/mvc_crud/app/views/user_view.py
# render_template() es una función de Flask
# que renderiza un template de Jinja2.
from flask import render_template


# La función `usuarios` recibe una lista de
# usuarios y renderiza el template `usuarios.html`
def usuarios(users):
    return render_template("usuarios.html", users=users, title="Lista de usuarios")


# La función `registro` renderiza el
# template `registro.html`
def registro():
    return render_template("registro.html", title="Registro de usuarios")


# La función `actualizar` recibe un usuario
# y renderiza el template `actualizar.html`
def actualizar(user):
    return render_template("actualizar.html", title="Actualizar usuario", user=user)

semana8/mvc_crud/app/templates/actualizar.html
{% extends 'base.html' %}

{% block content %}
<h2 class="subtitle is-2">Actualizar Usuario</h2>

<form method="post" action="/users/{{ user.id }}/update">
    <div class="field">
        <label for="first_name">Nombre:</label>
        <div class="control">
            <input type="text" id="first_name" name="first_name" 
            required class="input" value="{{ user.first_name }}">
        </div>
    </div>
    <div class="field">
        <label for="last_name">Apellido:</label>
        <div class="control">
            <input type="text" id="last_name" name="last_name" 
            required class="input" value="{{ user.last_name }}">
        </div>
    </div>
    <input type="submit" value="Actualizar" class="button is-primary">

{% endblock %}

semana8/mvc_crud/app/templates/base.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.0/css/bulma.min.css">
    <title>{{title}}</title>
</head>
<body>
    <h1 class="title">MVC</h1>
    <nav  class="breadcrumb" aria-label="breadcrumbs" >
        <div id="navbarBasicExample" class="navbar-menu">
            <div class="navbar-start">
                <a class="navbar-item" href="/">
                    {{ title.upper() }}
                </a>
                <a class="navbar-item" href="{{ url_for('user.create_user') }}">
                    Registrar Usuario
                </a>
                <a class="navbar-item" href="{{ url_for('user.list_users') }}">
                    Lista de Usuarios
                </a>
            </div>
        </div>
    </nav>
    <div class="columns is-mobile is-centered">
        <div class="column is-half">
            {% block content %}{% endblock %}
        </div>
    </div>
</body>
</html>

semana8/mvc_crud/app/templates/registro.html
{% extends 'base.html' %}

{% block content %}
<h2 class="subtitle is-2">Registrar Usuario</h2>
<form method="post">
    <div class="field" >
        <label for="first_name">Nombre:</label>
        <div class="control">
            <input type="text" id="first_name" name="first_name" required class="input">
        </div>
    </div>
    <div class="field">
        <label for="last_name">Apellido:</label>
        <div class="control">
            <input type="text" id="last_name" name="last_name" required class="input">
        </div>
    </div>
    <input type="submit" value="Registrar" class="button is-primary">
</form>
{% endblock %}

semana8/mvc_crud/app/templates/usuarios.html
{% extends 'base.html' %}

{% block content %}
<h2 class="subtitle is-2">Lista de Usuarios</h2>
    <!--Lista en una tarjeta donde cada usuario tenga sus datos y dos botones para editar y eliminar utilizando grid-->
    <div class="columns is-multiline">
        {% for user in users %}
            <div class="column is-one-third">
                <div class="card">
                    <div class="card-content">
                        <div class="content">
                            <p><strong>Nombre: {{ user.first_name }} </strong></p>
                            <p><strong>Apellido: {{ user.last_name }}</strong></p>
                            <div class="buttons">
                                <a href="{{ url_for('user.update_user', id=user.id) }}" 
                                class="button is-info">Editar</a>
                                <a href="{{ url_for('user.delete_user', id=user.id) }}" 
                                class="button is-danger">Eliminar</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}