semana8/mvc/app/models/user_model.py
from database import db
# `db.Model` es una clase base para todos los modelos de SQLAlchemy
# Define la clase `User` que hereda de `db.Model`
# `User` representa la tabla `users` en la base de datos
class User(db.Model):
    __tablename__ = 'users'
    # Define las columnas de la tabla `users`
    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String(50), nullable=False)
    last_name = db.Column(db.String(50), nullable=False)
    email = db.Column(db.String(50), nullable=False)
    contraseña = db.Column(db.String(50), nullable=False)
    Fecha_nacimiento = db.Column(db.Date, nullable=False)

    # Inicializa la clase `User`
    def __init__(self, first_name, last_name, email, contraseña, Fecha_nacimiento):
        self.first_name = first_name
        self.last_name = last_name
        self.email = email
        self.contraseña = contraseña
        self.Fecha_nacimiento = Fecha_nacimiento

    # Guarda un usuario en la base de datos
    def save(self):
        db.session.add(self)
        db.session.commit()

    # Obtiene todos los usuarios de la base de datos
    @staticmethod
    def get_all():
        return User.query.all()

semana8/mvc/app/controllers/user_controller.py
from flask import Blueprint, request, redirect, url_for
# Importamos la vista de usuarios
from views import user_view
# Importamos el modelo de usuario
from models.user_model import User

# Un Blueprint es un objeto que agrupa rutas y vistas
user_bp = Blueprint('user', __name__)

# Definimos las rutas "/" asociada a la funcion usuarios
# que nos devuelve la vista de usuarios
@user_bp.route('/')
def usuarios():
    # Obtenemos todos los usuarios
    users = User.get_all()
    # Llamamos a la vista de usuarios
    return user_view.usuarios(users)

# Definimos la ruta "/users" asociada a la función registro
# que nos devuelve la vista de registro
@user_bp.route('/users', methods=['GET','POST'])
def registro():
    if request.method == 'POST':
        # Obtenemos los datos del formulario
        first_name = request.form['first_name']
        last_name = request.form['last_name']
        email = request.form['email']
        contraseña = request.form['contraseña']
        Fecha_nacimiento = request.form['Fecha_nacimiento']
        # Creamos un nuevo usuario
        user = User(first_name, last_name, email, contraseña, Fecha_nacimiento)
        # Guardamos el usuario
        user.save()
        # Redirigimos a la vista de usuarios
        return redirect(url_for('user.usuarios'))
    # Llamamos a la vista de registro
    return user_view.registro()

semana8/mvc/app/views/user_view.py
# render_template() es una función de Flask
# que renderiza un template de Jinja2.
from flask import render_template


# La función `usuarios` recibe una lista de
# usuarios y renderiza el template `usuarios.html`
def usuarios(users):
    return render_template("usuarios.html", users=users)


# La función `registro` renderiza el
# template `registro.html`
def registro():
    return render_template("registro.html")

semana8/mvc/app/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <title>MVC</title>
</head>

<body>
    <h1>MVC</h1>
    <nav>
        <a href="{{ url_for('user.registro') }}">Registrar Usuario</a> |
        <a href="{{ url_for('user.usuarios') }}">Lista de Usuarios</a>
    </nav>
    <div>
        {% block content %}{% endblock %}
    </div>
</body>

</html>

semana8/mvc/app/templates/registro.html
{% extends 'base.html' %}

{% block content %}
<h2>Registrar Usuario</h2>
<form method="post">
    <label for="first_name">Nombre:</label>
    <input type="text" id="first_name" name="first_name" required><br>
    <label for="last_name">Apellido:</label>
    <input type="text" id="last_name" name="last_name" required><br>
    <label for="last_name">Email:</label>
    <input type="text" id="email" name="email" required><br>
    <label for="last_name">contraseña:</label>
    <input type="text" id="contraseña" name="contraseña" required><br>
    <label for="last_name">Fecha_nacimiento:</label>
    <input type="text" id="Fecha_nacimiento" name="Fecha_nacimiento" required><br>
    <input type="submit" value="Registrar">
    
</form>
{% endblock %}

semana8/mvc/app/templates/usuarios.html
{% extends 'base.html' %}

{% block content %}
<h2>Lista de Usuarios</h2>
<ul>
    {% for user in users %}
        <li>{{ user.first_name }} {{ user.last_name }} {{ user.email }} {{ user.contraseña }} {{ user.Fecha_nacimiento }}</li>
    {% endfor %}
</ul>
{% endblock %}