semana11/web_app_role/app/controllers/animal_controller.py
from flask import Blueprint, request, redirect, url_for, flash, jsonify
from flask_login import login_required, current_user
from models.animal_model import Animal
from views import animal_view

# Importamos el decorador de roles
from utils.decorators import role_required

animal_bp = Blueprint("animal", __name__)


@animal_bp.route("/animals")
@login_required
def list_animals():
    animals = Animal.get_all()
    return animal_view.list_animals(animals)


@animal_bp.route("/animals/create", methods=["GET", "POST"])
@login_required
@role_required("admin")
def create_animal():
    if request.method == "POST":
        if current_user.has_role("admin"):
            name = request.form["name"]
            species = request.form["species"]
            age = int(request.form["age"])
            animal = Animal(name=name, species=species, age=age)
            animal.save()
            flash("Animal creado exitosamente", "success")
            return redirect(url_for("animal.list_animals"))
        else:
            return jsonify({"message": "Unauthorized"}), 403
    return animal_view.create_animal()


@animal_bp.route("/animals/<int:id>/update", methods=["GET", "POST"])
@login_required
@role_required("admin")
def update_animal(id):
    animal = Animal.get_by_id(id)
    if not animal:
        return "Animal no encontrado", 404
    if request.method == "POST":
        if current_user.has_role("admin"):
            name = request.form["name"]
            species = request.form["species"]
            age = int(request.form["age"])
            animal.update(name=name, species=species, age=age)
            flash("Animal actualizado exitosamente", "success")
            return redirect(url_for("animal.list_animals"))
        else:
            return jsonify({"message": "Unauthorized"}), 403
    return animal_view.update_animal(animal)


@animal_bp.route("/animals/<int:id>/delete")
@login_required
@role_required("admin")
def delete_animal(id):
    animal = Animal.get_by_id(id)
    if not animal:
        return "Animal no encontrado", 404
    if current_user.has_role("admin"):
        animal.delete()
        flash("Animal eliminado exitosamente", "success")
        return redirect(url_for("animal.list_animals"))
    else:
        return jsonify({"message": "Unauthorized"}), 403

semana11/web_app_role/app/controllers/user_controller.py
from flask import Blueprint, request, redirect, url_for, flash
from flask_login import login_user, logout_user, login_required, current_user
from werkzeug.security import check_password_hash

# Importamos el decorador de roles
from utils.decorators import role_required

# Importamos la vista de usuarios
from views import user_view

# Importamos el modelo de usuario
from models.user_model import User

# Un Blueprint es un objeto que agrupa
# rutas y vistas
user_bp = Blueprint("user", __name__)


# Ruta de la página raíz redirige a
# la página de inicio de sesión
@user_bp.route("/")
def index():
    if current_user.is_authenticated:
        return redirect(url_for("user.profile", id=current_user.id))
    return redirect(url_for("user.login"))


@user_bp.route("/users")
@login_required
def list_users():
    # Obtenemos todos los usuarios
    users = User.get_all()
    # Llamamos a la vista de usuarios
    return user_view.usuarios(users)


# Definimos la ruta "/users" asociada a la función registro
# que nos devuelve la vista de registro
@user_bp.route("/users/create", methods=["GET", "POST"])
def create_user():
    if request.method == "POST":
        # Obtenemos los datos del formulario
        first_name = request.form["first_name"]
        last_name = request.form["last_name"]
        username = request.form["username"]
        password = request.form["password"]
        role = request.form["role"]
        existing_user = User.query.filter_by(username=username).first()
        if existing_user:
            flash("El nombre de usuario ya está en uso", "error")
            return redirect(url_for("user.create_user"))
        # Creamos un nuevo usuario
        user = User(first_name, last_name, username, password, role=role)
        user.set_password(password)
        # Guardamos el usuario
        user.save()
        flash("Usuario registrado exitosamente", "success")
        return redirect(url_for("user.list_users"))
    # Llamamos a la vista de registro
    return user_view.registro()


# Actualizamos la información del usuario por su id
# Ya estamos en la vista de actualizar
# por lo que obtenemos los datos del formulario
# y actualizamos la información del usuario
@user_bp.route("/users/<int:id>/update", methods=["GET", "POST"])
@login_required
@role_required("admin")
def update_user(id):
    user = User.get_by_id(id)
    if not user:
        return "Usuario no encontrado", 404
    if request.method == "POST":
        # Obtenemos los datos del formulario
        first_name = request.form["first_name"]
        last_name = request.form["last_name"]
        # Actualizamos los datos del usuario
        user.first_name = first_name
        user.last_name = last_name
        # Guardamos los cambios
        user.update()
        return redirect(url_for("user.list_users"))
    return user_view.actualizar(user)


@user_bp.route("/users/<int:id>/delete")
@login_required
@role_required("admin")
def delete_user(id):
    user = User.get_by_id(id)
    if not user:
        return "Usuario no encontrado", 404
    user.delete()
    return redirect(url_for("user.list_users"))


# Ruta para el inicio de sesión
@user_bp.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        username = request.form["username"]
        password = request.form["password"]
        user = User.get_user_by_username(username)
        if user and check_password_hash(user.password_hash, password):
            login_user(user)
            flash("Inicio de sesión exitoso", "success")
            if user.has_role("admin"):
                # Redirigir a su perfil si el usuario es de rol "admin"
                return redirect(url_for("user.list_users"))
            else:
                # Redirigir a la lista de usuarios para otros roles
                return redirect(url_for("user.profile", id=user.id))
        else:
            flash("Nombre de usuario o contraseña incorrectos", "error")
    return user_view.login()


# Ruta para cerrar sesión
@user_bp.route("/logout")
@login_required
def logout():
    logout_user()
    flash("Sesión cerrada exitosamente", "success")
    return redirect(url_for("user.login"))


@user_bp.route("/profile/<int:id>")
@login_required
def profile(id):
    user = User.get_by_id(id)
    return user_view.perfil(user)

semana11/web_app_role/app/views/animal_view.py
from flask import render_template
from flask_login import current_user


# La función `list_animals` recibe una lista de
# animales y renderiza el template `animales.html`
def list_animals(animals):
    return render_template(
        "animals.html",
        animals=animals,
        title="Lista de animales",
        current_user=current_user,
    )


# La función `create_animal` renderiza el
# template `create_animal.html` o devuelve un JSON
# según la solicitud
def create_animal():
    return render_template(
        "create_animal.html", title="Crear Animal", current_user=current_user
    )


# La función `update_animal` recibe un animal
# y renderiza el template `update_animal.html`
def update_animal(animal):
    return render_template(
        "update_animal.html",
        title="Editar Animal",
        animal=animal,
        current_user=current_user,
    )

semana11/web_app_role/app/templates/actualizar.html
{% extends 'base.html' %}

{% block content %}
<h2 class="subtitle is-2">Actualizar Usuario</h2>

<form method="post" action="/users/{{ user.id }}/update">
    <div class="field">
        <label for="first_name">Nombre:</label>
        <div class="control">
            <input type="text" id="first_name" name="first_name" 
            required class="input" value="{{ user.first_name }}">
        </div>
    </div>
    <div class="field">
        <label for="last_name">Apellido:</label>
        <div class="control">
            <input type="text" id="last_name" name="last_name" 
            required class="input" value="{{ user.last_name }}">
        </div>
    </div>
    <div class="field">
        <label for="username">Nombre de Usuario:</label>
        <div class="control">
            <input type="text" id="username" name="username" 
            required class="input" value="{{ user.username }}">
        </div>
    </div>
    
    <div class="field">
        <label for="role">Rol:</label>
        <div class="control">
            <div>
                <input type="text" id="role" name="role" 
                required class="input" value="{{ user.role }}">
        </div>
    </div>
    <input type="submit" value="Actualizar" class="button is-primary">

{% endblock %}

semana11/web_app_role/app/templates/animals.html
{% extends 'base.html' %}

{% block content %}
<h2 class="subtitle is-2">Lista de Animales</h2>
    <!-- Lista en una tarjeta donde cada animal tenga sus datos y botones para editar y eliminar, solo visibles para administradores -->
    <div class="columns is-multiline">
        {% for animal in animals %}
            <div class="column is-one-third">
                <div class="card">
                    <div class="card-content">
                        <div class="content">
                            <p><strong>Nombre: {{ animal.name }} </strong></p>
                            <p><strong>Especie: {{ animal.species }}</strong></p>
                            <p><strong>Edad: {{ animal.age }}</strong></p>
                            <div class="buttons">
                                {% if current_user.has_role('admin') %}
                                    <a href="{{ url_for('animal.update_animal', id=animal.id) }}" 
                                    class="button is-info">Editar</a>
                                    <a href="{{ url_for('animal.delete_animal', id=animal.id) }}" 
                                    class="button is-danger">Eliminar</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

semana11/web_app_role/app/templates/base.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.0/css/bulma.min.css">
    <title>{{ title }}</title>
</head>
<body>
    <h1 class="title">MVC</h1>
    {% if current_user.is_authenticated %}
    <nav class="breadcrumb" aria-label="breadcrumbs">
        <div id="navbarBasicExample" class="navbar-menu">
            <div class="navbar-start">
                {% if current_user.has_role("admin") %}
                <a class="navbar-item" href="{{ url_for('user.list_users') }}">
                    Lista de Usuarios
                </a>
                <a class="navbar-item" href="{{ url_for('animal.create_animal') }}">
                    Crear Animal
                </a>
                {% endif %}
                <a class="navbar-item" href="{{ url_for('user.profile', id=current_user.id) }}">
                    Perfil
                </a>
                <a class="navbar-item" href="{{ url_for('animal.list_animals') }}">
                    Lista de Animales
                </a>
                <a class="navbar-item" href="{{ url_for('user.logout') }}">
                    Cerrar Sesión
                </a>
            </div>
        </div>
    </nav>
    {% endif %}
    <div class="columns is-mobile is-centered">
        <div class="column is-half">
            {% block content %}{% endblock %}
        </div>
    </div>
</body>
</html>

semana11/web_app_role/app/templates/create_animal.html
{% extends 'base.html' %}

{% block content %}
<h2 class="subtitle is-2">Registrar Animal</h2>
<form method="post">
    <div class="field">
        <label for="name">Nombre:</label>
        <div class="control">
            <input type="text" id="name" name="name" required class="input">
        </div>
    </div>
    <div class="field">
        <label for="species">Especie:</label>
        <div class="control">
            <input type="text" id="species" name="species" required class="input">
        </div>
    </div>
    <div class="field">
        <label for="age">Edad:</label>
        <div class="control">
            <input type="number" id="age" name="age" required class="input">
        </div>
    </div>
    <input type="submit" value="Registrar" class="button is-primary">
</form>
{% endblock %}

semana11/web_app_role/app/templates/login.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="title">Iniciar Sesión</h1>
    <div class="columns is-mobile is-centered">
        <div class="column is-half">
            <form method="post">
                <div class="field">
                    <label class="label">Nombre de Usuario</label>
                    <div class="control">
                        <input class="input" type="text" name="username" required>
                    </div>
                </div>
                <div class="field">
                    <label class="label">Contraseña</label>
                    <div class="control">
                        <input class="input" type="password" name="password" required>
                    </div>
                </div>
                <div class="field is-grouped">
                    <div class="control">
                        <button class="button is-primary" type="submit">Iniciar Sesión</button>
                    </div>
                    <div class="control">
                        <a href="{{ url_for('user.create_user') }}" class="button is-info">Crear Usuario</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

semana11/web_app_role/app/templates/profile.html
{% extends 'base.html' %}

{% block content %}
<h2 class="subtitle is-2">Perfil de Usuario</h2>
<div class="card">
    <div class="card-content">
        <div class="content">
            <p><strong>Nombre:</strong> {{ user.first_name }}</p>
            <p><strong>Apellido:</strong> {{ user.last_name }}</p>
            <p><strong>Nombre de Usuario:</strong> {{ user.username }}</p>
            <p><strong>Rol:</strong> {{ user.role }}</p>
        </div>
    </div>
</div>
{% endblock %}

semana11/web_app_role/app/templates/registro.html
{% extends 'base.html' %}

{% block content %}
<h2 class="subtitle is-2">Registrar Usuario</h2>
<form method="post">
    <div class="field">
        <label for="first_name">Nombre:</label>
        <div class="control">
            <input type="text" id="first_name" name="first_name" 
            required class="input">
        </div>
    </div>
    <div class="field">
        <label for="last_name">Apellido:</label>
        <div class="control">
            <input type="text" id="last_name" name="last_name" 
            required class="input">
        </div>
    </div>
    <div class="field">
        <label for="username">Nombre de Usuario:</label>
        <div class="control">
            <input type="text" id="username" name="username" 
            required class="input">
        </div>
    </div>
    <div class="field">
        <label for="password">Contraseña:</label>
        <div class="control">
            <input type="password" id="password" name="password" 
            required class="input">
        </div>
    </div>
    <div class="field">
        <label for="role">Rol:</label>
        <div class="control">
            <input type="text" id="role" name="role" 
            required class="input">
        </div>
    </div>
    <input type="submit" value="Registrar" class="button is-primary">
</form>
{% endblock %}

semana11/web_app_role/app/templates/update_animal.html
{% extends 'base.html' %}

{% block content %}
<h2 class="subtitle is-2">Editar Animal</h2>
<form method="post">
    <div class="field">
        <label for="name">Nombre:</label>
        <div class="control">
            <input type="text" id="name" name="name" required class="input" value="{{ animal.name }}">
        </div>
    </div>
    <div class="field">
        <label for="species">Especie:</label>
        <div class="control">
            <input type="text" id="species" name="species" required class="input" value="{{ animal.species }}">
        </div>
    </div>
    <div class="field">
        <label for="age">Edad:</label>
        <div class="control">
            <input type="number" id="age" name="age" required class="input" value="{{ animal.age }}">
        </div>
    </div>
    <input type="submit" value="Guardar Cambios" class="button is-primary">
</form>
{% endblock %}

semana11/web_app_role/app/templates/usuarios.html
{% extends 'base.html' %}

{% block content %}
<h2 class="subtitle is-2">Lista de Usuarios</h2>
    <!--Lista en una tarjeta donde cada usuario tenga sus datos y dos botones para editar y eliminar utilizando grid-->
    <div class="columns is-multiline">
        {% for user in users %}
            <div class="column is-one-third">
                <div class="card">
                    <div class="card-content">
                        <div class="content">
                            <p><strong>Nombre: {{ user.first_name }} </strong></p>
                            <p><strong>Apellido: {{ user.last_name }}</strong></p>
                            <div class="buttons">
                                <a href="{{ url_for('user.update_user', id=user.id) }}" 
                                class="button is-info">Editar</a>
                                <a href="{{ url_for('user.delete_user', id=user.id) }}" 
                                class="button is-danger">Eliminar</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}